# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 04 Dec 2018 00:11:39 +0000
*               @ALL          1
*               @user         8
