<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Tue, 04 Dec 2018 00:11:39 +0000
 */
$conf['title'] = 'tilde.institute';
$conf['lang'] = 'en';
$conf['license'] = 'cc-by-nc-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
